#!/bin/bash

ORIGIN=$1
ID=$2

if [[ -n $(git branch -v | grep pr/${ID}) ]]; then
  git branch -D pr/${ID}
fi

git fetch ${ORIGIN} refs/pull/${ID}/head
git checkout -b pr/${ID} FETCH_HEAD^
git pull ${ORIGIN} refs/pull/${ID}/head